### ISSUE TITLE
feat(studioPage): 헤더 UI 개발

### ISSUE THREAD

**Issue by DonggyunKim00** [9oormthon-2523/chzzk-clone#1]
## 📝 Description
- 스튜디오 페이지 헤더 개발에 관한 내용입니다.
- 페이지 경로는 `/studio/[user]` 이며, user의 값은 유저의 고유 아이디 값 입니다.
- 로그인 되었다고 가정하고 작업하였습니다.

## ✅ Todo
- [x] UI 디자인 구현
- [x] 버튼 hover시 동작 내용 설명 띄우기
- [x] 네비게이션 메뉴 확장, 축소 구현
- [x] 프로필 클릭시 리스트 확장 기능 구현

## ETC
x
