### ISSUE TITLE
feat(StudioPage): 대시보드 UI 구현

### ISSUE THREAD

**Issue by ki2183** [9oormthon-2523/chzzk-clone#20]
## 📝 Description
스튜디오 페이지 대시보드 UI를 구현합니다

## ✅ Todo
- [x] 페이지 와이어 프레임 구현
- [x] title, info, button 구현
- [x] 공지사항 컴포넌트 구현
- [x] svg 추출

![image](https://github.com/user-attachments/assets/754a978e-672e-4b34-ba27-a1e57dc7e49d)

## ETC
