### ISSUE TITLE
feat(livePage): 채팅 관련 기본 세팅

### ISSUE THREAD

**Issue by AhnRian** [9oormthon-2523/chzzk-clone#21]
## 📝 Description
채팅 관련 기본 세팅을 진행합니다.

## ✅ Todo
- [x] 채팅 테이블 설정
- [x] 채팅 관련 supabase client 다운
- [x] 환경 변수 설정
- [x] 테스트 채팅 컴포넌트 구현

## ETC
https://f-lab.kr/insight/real-time-chat-application-with-nextjs-and-supabase-20241104
