### ISSUE TITLE
feat(studioPage): 전체 레이아웃 조정

### ISSUE THREAD

**Issue by DonggyunKim00** [9oormthon-2523/chzzk-clone#27]
## 📝 Description
1. UI 구성 및 폴더 구조화 작업
2. 스튜디오 페이지에 접근 시 유저의 uid를 통해 유저의 정보를 받아온 후, 현재 쿠키 스토리지에 존재하는 유저의 정보와비교한다.
만약 유저의 정보와 유저의 uid를 통해 가져온 정보와 일치한다면 접근을 허용하고, 일치하지 않는다면 접근을 허용하지 않는다.

## ✅ Todo
- [x] /studio/[user] -> /studio/[uid] 로 동적 경로 폴더이름 변경
- [x] studio 페이지 폴더 구조 재구성
- [x] 대시보드 UI 배치 및 라우트 정의
- [x] 페이지 유저 고유의 uid를 통한 동적 라우트 정의 
- [x] 페이지 라우트와 쿠키 내부 값의 유저 정보와 일치하지 않는다면 로그인 권장 팝업 UI 띄우기

## ETC
<img width="100%" alt="스크린샷 2024-12-25 오후 10 40 39" src="https://github.com/user-attachments/assets/b50180fd-87ef-4273-a386-827b7ad971e8" />
