### ISSUE TITLE
feat(studioPage): navigation UI 구현

### ISSUE THREAD

**Issue by DonggyunKim00** [9oormthon-2523/chzzk-clone#4]
## 📝 Description

- 스튜디오 페이지의 좌측에 위치한 네비게이션 사이드바 입니다. 좌측 상단의 햄버거 바를 이용하여 네비게이션을 축소, 확장할 수 있습니다.
- 메뉴 구성: `대시보드`, `방송관리`, `시청자관리`
- 각 메뉴 버튼 클릭 시 세부 메뉴를 띄워줍니다.
- 세부 메뉴 클릭 시 각 라우트로 이동하며, 이동된 라우트 경로와 네비게이션 메뉴바가 일치한 내용이라면 버튼의 이미지와 텍스트 색상이 변경됩니다.

## ✅ Todo
- [x] 메뉴 UI 구성 및 페이지 내부에 네비게이션 배치
- [x] 메뉴 확장, 축소 전역 상태값을 사용하여 확장, 축소 애니메이션 구현 
- [x] 메뉴 클릭 시 세부 메뉴 UI 띄우기
- [x] 각 메뉴 버튼에 대하여 라우트 관련 처리
- [x] 메뉴 축소되었을때, hover시 설명 띄우는 UI 구현

## ETC

<div align='center'>
<img width="292" alt="image" src="https://github.com/user-attachments/assets/319150cc-c3fa-4fe3-b5be-30326be2cdf7" />
<img width="120" alt="스크린샷 2024-12-16 오후 4 39 57" src="https://github.com/user-attachments/assets/10232907-2291-45c0-819e-567bf1a4d409" />
</div>
