### ISSUE TITLE
feat(studioPage/streamingTest): 미들웨어 테스트

### ISSUE THREAD

**Issue by ki2183** [9oormthon-2523/chzzk-clone#41]
## 📝 Description
agora 작동 테스트

## ✅ Todo
- [x]  StudioPage/_components/streamingBtn.tsx: 라이브 시작 버튼에 기능 연결
- [x] LivePage: 채널 입장 후 라이브 스트리밍 확인
- [x] 라이브 스트리밍 테스트 실행

## ETC
머지 X 기능 확인용
