### ISSUE TITLE
feat(studioPage): 네비게이션 라우트에 따른 텍스트 색상 변경

### ISSUE THREAD

**Issue by DonggyunKim00** [9oormthon-2523/chzzk-clone#45]
## 📝 Description
라우트에 따른 네비게이션 메뉴 버튼들의 색상 변화를 치지직과 동일하게 조정할 예정입니다.

## ✅ Todo
- [x] 서브메뉴 모듈화
- [x] 네비게이션 메뉴버튼 도메인 match 로직 else 문 추가
- [x] `MenuButtonBox` 컴포넌트 color props 추가
- [x] 네비게이션 라우트에 따른 텍스트 색상 변경

## ETC
X
