### ISSUE TITLE
feat(studioPage): 라우트 관련 로직 구현

### ISSUE THREAD

**Issue by DonggyunKim00** [9oormthon-2523/chzzk-clone#49]
## 📝 Description
스튜디오 페이지에서 라우트 관련 로직을 처리합니다.

## ✅ Todo
- [x] `/studio` 라우팅시 쿠키값에 따라 `/studio/[uid]` 로 리다이렉팅 쿠키값의 유저가 null 이라면 로그인 권장 팝업 띄우기
- [x] 사용자의 브라우저 환경에 따라 세부적인 조건부 UI 렌더링 구현
  - [x] 로그인이 된 상태(supabase.auth.getUser() 가 null이 아닌 상태) 에서 다른 uid 스튜디오로 접근시 block UI 띄우기
    - [x] block UI 구현  
  - [x] 로그인이 안된 상태(supabase.auth.getUser() 가 null인 상태) 에서 /studio 와 그 하위 경로에 접근시 로그인 권장 팝업 띄우기
    - [x] 로그인 권장 팝업에서 라우트를 이동시킬때 메인페이지의 로그인 모달 띄우기

## ETC
X
