### ISSUE TITLE
feat(studioPage): 유저 토큰값을 이용한 프로필 DB 연동

### ISSUE THREAD

**Issue by DonggyunKim00** [9oormthon-2523/chzzk-clone#51]
## 📝 Description
supabase 로그인을 이용하여 토큰값을 발급받고 해당 토큰을 이용해 유저의 프로필에 접근할 수 있는 DB 테이블을 만들고 이를 이용해 헤더 프로필을 구현한다.
추가적으로 프로필 클릭시 메뉴

## ✅ Todo
- [x] supabaes Auth DB를 이용한 프로필 `supabse.auth` 데이터 동적 할당
- [x] 메뉴에 존재하는 채널로 이동하기 버튼 클릭시`/channel/[uid]` 라우팅하기
- [x] supabase 로그아웃 API 연동

## ETC
<img width="460" alt="스크린샷 2024-12-29 오후 5 44 36" src="https://github.com/user-attachments/assets/885d5489-3707-4201-a8d0-598824c0fad1" />
